[project]
name = "python-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "essentia-tensorflow>=2.1b6.dev1177",
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "yt-dlp>=2025.6.30",
]
